apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: enterprise
  namespace: ${ENTERPRISE_NAMESPACE}

spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: enterprise
  targetCPUUtilizationPercentage: 70
