apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: io-enterprise
  namespace: ${IO_ENTERPRISE_NAMESPACE}

spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: io-enterprise
  targetCPUUtilizationPercentage: 70