apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: enterprise
  namespace: ${ENTERPRISE_NAMESPACE}
  labels:
    app: enterprise
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #    nginx.ingress.kubernetes.io/app-root: /SUNDEEP/app/index.html
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
spec:
  #  ingressClassName: nginx
  #  tls:
  #    - hosts:
  #      - com.TOMCAT.net
  #      secretName: secret
  rules:
    - host: enterprise.TOMCAT.com
      http:
        paths:
          - path:
            #      - path: /SUNDEEP(.*)
            #        pathType: Prefix
            backend:
              serviceName: enterprise
              servicePort: 8080
