pipeline{
    
    environment {
        imagename = "docker/io-enterprise-docker"
        dockergitrepo = 'io-enterprise-docker'
        registryCredential = 'jenkins-jfrog'
        dockerImage = ''
    }
    
    agent { 
      kubernetes {
            defaultContainer 'docker'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    buildType: docker
spec:
  containers:
  - name: docker
    image: simeio.jfrog.io/docker/docker:20.10.10-dind
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-sock-volume
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
  imagePullSecrets:
    - name: regcred
"""
        }
    }
    triggers {
                cron('H 15 * * *')
    }

    stages {
        stage('Build Repository Checkout') {
            steps{
                // Clean the workspace
                cleanWs()

                // Check out the build repository
                checkout([$class: 'GitSCM', branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[credentialsId: 'bitbucket-jenkins', url: 'https://bitbucket.org/TOMCAT/' + dockergitrepo + '.git']]])
            }
        }
        stage('Get Build Version - Develop') {
            steps {
                //Check out the binary repo
                checkout([$class: 'GitSCM', branches: [[name: '*/development']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'binaryrepo'], [$class: 'CleanBeforeCheckout'], [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'pom.xml']]]], userRemoteConfigs: [[credentialsId: 'bitbucket-jenkins', url: 'https://bitbucket.org/TOMCAT/enterprise.git']]])
            }
        }

        stage ('Set Build Version Environment Variable') {

            steps {
                // Set the build version environment variable
                script{
	                //NEED TO UPDATE THE FOLLOWING TO GREP THE POM.XML PROPERLY TO OBTAIN THE VERSION, THEN IT SHOULD BE ACTIVATED
                    env.BLDVER = sh(script: 'cat binaryrepo/pom.xml | grep \'version\' | grep -o -E \'[0-9]+\\.[0-9]+\\.[0-9]+(\\-SNAPSHOT)?\'', returnStdout: true).trim()

                }

                // Print the determine build version
                sh 'echo Building version $BLDVER'
            }
        }

        /* stage('Download Artifacts') {
            // steps {
              //Get the Artifact from Artifactory

              //Use the following pattern for Maven-generated artifacts
                //rtDownload (
                   //serverId: 'TOMCAT-artifactory',
                    //spec: ''' {
                            //"files": [
                                //{
                                    //"pattern": "repo/com/TOMCAT/$BLDVER/$BLDVER.zip"
                                    //"flat": "true",
			                        //"build":"enterprise/LATEST"
                                //}
                            //]
                    //} '''
                //)

                //Retrieve non-Maven SNAPSHOT artifacts via curl to ensure latest SNAPSHOT build is resolved. Need the -L option to follow any redirects
                //withCredentials([usernamePassword(credentialsId: 'jenkins_jfrog', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    //sh 'curl -L -u $USERNAME:$PASSWORD -O https://TOMCAT.jfrog.io/artifactory/libs-releases-local/com/TOMCAT/$BLDVER/conf'
                    //sh 'curl -L -u $USERNAME:$PASSWORD -O https://TOMCAT.jfrog.io/artifactory/libs-releases-local/com/TOMCAT/$BLDVER/TOMCAT.war'
                    //sh 'curl -L -u $USERNAME:$PASSWORD -O https://TOMCAT.jfrog.io/artifactory/libs-releases-local/com/TOMCAT/$BLDVER/SUNDEEP.war'
                //}
            //}
        //}

        //stage ('download dependencies for image') {
		     //steps {
			    //withCredentials([usernamePassword(credentialsId: 'bitbucket-jenkins', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    //sh 'curl -L -u $USERNAME:$PASSWORD -O https://TOMCAT.jfrog.io/artifactory/docker-images-local/com/TOMCAT/7/7.zip'
				//}
				//sh 'ls TOMCAT-*.zip'
				//sh 'unzip 7.zip'
			 //}
        //}*/
        stage('Download Artifacts') {
                     steps {
                     // Get the Artifact from Artifactory
                        rtServer (
                            id: 'ARTIFACTORY_SERVER',
                            url: 'https://TOMCAT.jfrog.io/artifactory',
                            credentialsId: 'jenkins-jfrog'
                        )

                     // Use the following pattern for Maven-generated artifacts
                        rtDownload (
                           serverId: 'ARTIFACTORY_SERVER',
                            spec: ''' {
                                    "files": [
                                        {
                                            "pattern": "repo/com/TOMCAT/$BLDVER/$BLDVER.zip",
                                            "sortBy": ["created"],
                                            "sortOrder": "desc",
                                            "limit": 1,
                                            "target": "binaryrepo/",
                                            "flat": "true"
                                        }
                                    ]
                            } '''
                        )

                        rtDownload (
                           serverId: 'ARTIFACTORY_SERVER',
                            spec: ''' {
                                    "files": [
                                        {
                                            "pattern": "repo/com/TOMCAT/$BLDVER/$BLDVER.war",
                                            "sortBy": ["created"],
                                            "sortOrder": "desc",
                                            "limit": 1,
                                            "target": "binaryrepo/",
                                            "flat": "true"
                                        }
                                    ]
                            } '''
                        )
                        rtDownload (
                           serverId: 'ARTIFACTORY_SERVER',
                            spec: ''' {
                                    "files": [
                                        {
                                            "pattern": "repo/com/TOMCAT/$BLDVER/$BLDVER.war",
                                            "sortBy": ["created"],
                                            "sortOrder": "desc",
                                            "limit": 1,
                                            "target": "binaryrepo/",
                                            "flat": "true"
                                        }
                                    ]
                            } '''
                        )
                     }
                }

                stage ("Building Docker Image") {
                    steps {

                        script {
                            sh ("cp binaryrepo/TOMCAT-*.war TOMCAT.war")
                            sh ("cp binaryrepo/SUNDEEP-*.war SUNDEEP.war")
                            sh ("cp binaryrepo/$BLDVER.zip .")
                            sh ("unzip $BLDVER.zip")
                            sh ("rm -rf conf/jdbc.properties")
                            sh ("docker build --network=host -t " + imagename + " .")
                            dockerImage = docker.build imagename
                        }
                    }
                }

                stage ("Push Docker Image to Registry") {
                    steps {
                        script {
                            docker.withRegistry('http://TOMCAT.jfrog.io/artifactory', registryCredential) {
                            dockerImage.push('$BLDVER')
                            dockerImage.push('latest')
                            }
                        }
                    }
                }
            }
        }
