apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: jenkins
type: Opaque
stringData:
  JENKINS_ADMIN_ID: replaceme
  JENKINS_ADMIN_PASSWORD: replaceme
  JENKINS_SERVICE_ACCOUNT_K8: replaceme
  JENKINS_SERVICE_ACCOUNT_K8_PASSWORD: replaceme
  JENKINS_FS_ACCOUNT_CREDENTIAL: replaceme
  JENKINS_SERVICE_ACCOUNT_JFROG: replaceme
  JENKINS_SERVICE_ACCOUNT_JFROG_PASSWORD: replaceme
  JENKINS_SERVICE_ACCOUNT_BITBUCKET: replaceme
  JENKINS_SERVICE_ACCOUNT_BITBUCKET_PASSWORD: replaceme
