apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jenkins-secrets.yaml
  - ../../base
  
patches:
  - jenkins-persistent-volume.yaml
  - jenkins-ingress.yaml
  - jenkins-configmap.yaml
  - jenkins-deployment.yaml
